CSP_GOOGLE = "google"
CSP_DROPBOX = "dropbox"

DOWNLOAD_FILES_FOLDER = "files"
DOWNLOAD_HISTORY_FOLDER = "history"

#downloader
THREAD_NOTCLICKED = -1
THREAD_CLICKED = 0
THREAD_VERIFY_CRED = 1
THREAD_DOWN_META = 2
THREAD_COMPUTING = 3
THREAD_DOWN_FH = 4
THREAD_TS = 5
THREAD_STOP = 6
TEST_THREAD_SLEEP_TIME = 1

#browserfile
HISTORY_FORM_CHROME = 0
HISTORY_FORM_FF = 1
HISTORY_FORM_TH = 2

# cloudservice
CS_SEARCH_TYPE_EMAIL = 0
CS_SEARCH_TYPE_FILENAME = 1
CS_SEARCH_TYPE_GIVENNAME = 2
CS_SEARCH_TYPE_ALL = 3

CS_SEARCH_FILTER_DELETED = 0
CS_SEARCH_FILTER_MIME = 1
CS_SEARCH_FILTER_ALL = 2

CS_RES_CHOICES = ((CS_SEARCH_FILTER_DELETED,'Deleted File'),(CS_SEARCH_FILTER_MIME,'MIME Type'),(CS_SEARCH_FILTER_ALL,'All'))
CS_FORM_TYPE = ((CS_SEARCH_TYPE_EMAIL,'E-Mail'),(CS_SEARCH_TYPE_FILENAME,'File Name'),(CS_SEARCH_TYPE_GIVENNAME,'Given Name'),(CS_SEARCH_TYPE_ALL,'All'))

#comparator
ALLOWED_MIME_TYPE = ("application/pdf","image/jpeg","image/png","image/gif","image/bmp")

#comparator
VERIFY_CHOICE_METADATA = 1
VERIFY_CHOICE_FILES = 2
VERIFY_CHOICE_FILESHISTORY = 3

VERIFY_CHOICES = ((VERIFY_CHOICE_METADATA,"Metadata"),(VERIFY_CHOICE_FILES,"Files"),(VERIFY_CHOICE_FILESHISTORY,"Files+History (it can take a lot of time)"))

