THREAD_NOTCLICKED = -1
THREAD_CLICKED = 0
THREAD_VERIFY_CRED = 1
THREAD_DOWN_META = 2
THREAD_COMPUTING = 3
THREAD_DOWN_FH = 4
THREAD_TS = 5
THREAD_STOP = 6
TEST_THREAD_SLEEP_TIME = 1

CSP_GOOGLE = "google"
CSP_DROPBOX = "dropbox"

